# Generated by Django 4.0.2 on 2022-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('website', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('industryList', models.CharField(max_length=155)),
            ],
        ),
    ]
